/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:499342a2-f95f-42d9-8c15-f80cef3a0736",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_MsrHR6mAR",
    "aws_user_pools_web_client_id": "6hbr0o5hrn2dq54180qtv06v8n",
    "oauth": {}
};


export default awsmobile;
